# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicles", "0002_vehicle_last_serviced"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="service_interval_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=180,
                help_text="Days between service reminders. Default 180 (6 months).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_reminder_sent",
            field=models.DateField(
                blank=True,
                help_text="Last date a service-due reminder was sent; avoids spam.",
                null=True,
            ),
        ),
    ]
