# Generated by Django 4.2.16 on 2026-02-10 14:45

from collections import defaultdict

from django.db.models import Q
from django.db import migrations, models
from django.utils import timezone


def backfill_remaining_invoice_display_numbers(apps, schema_editor):
    """Backfill any invoices with NULL or empty display_number before making field non-nullable."""
    import re
    Invoice = apps.get_model("Invoices", "Invoice")
    DisplayNumberSequence = apps.get_model("common", "DisplayNumberSequence")
    qs = Invoice.objects.filter(Q(display_number__isnull=True) | Q(display_number="")).order_by("created_at")
    if not qs.exists():
        return
    by_year = defaultdict(list)
    for inv in qs:
        year = inv.created_at.year if inv.created_at else timezone.now().year
        by_year[year].append(inv)
    for year, invoices in by_year.items():
        # Find max existing sequence for this year (from populated invoices or DisplayNumberSequence)
        max_num = 0
        for inv in Invoice.objects.exclude(Q(display_number__isnull=True) | Q(display_number="")):
            m = re.match(rf"^INV-{year}-(\d+)$", inv.display_number or "")
            if m:
                max_num = max(max_num, int(m.group(1)))
        seq = DisplayNumberSequence.objects.filter(prefix="INV", year=year).first()
        if seq:
            max_num = max(max_num, seq.last_value)
        for i, inv in enumerate(invoices, start=1):
            inv.display_number = f"INV-{year}-{max_num + i:05d}"
            inv.save(update_fields=["display_number"])
        DisplayNumberSequence.objects.update_or_create(
            prefix="INV", year=year, defaults={"last_value": max_num + len(invoices)}
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_backfill_invoice_display_numbers'),
    ]

    operations = [
        migrations.RunPython(backfill_remaining_invoice_display_numbers, noop),
        migrations.AlterField(
            model_name='invoice',
            name='display_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable ID, e.g. INV-2025-00001', max_length=20, unique=True),
        ),
    ]
