# Generated by Django 4.2.16 on 2026-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_fmsi_application_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, db_index=True, help_text='Product type from catalog (e.g. BRAKEPAD, DISK). From Excel PRODUCT column.', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.TextField(blank=True, help_text='Vehicle models this product applies to, comma-separated (e.g. Toyota Corolla 2009-2019, Honda Civic)'),
        ),
    ]
