# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0005_add_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional product image. Managed via Django admin.",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
