# Generated by Django - SMS Blast for promotional notifications

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Promotions", "0002_promotion_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSBlast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[("all", "All customers"), ("opt_in", "Opt-in only"), ("site", "Site-specific")],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0, help_text="Customers matched by audience.")),
                ("sent_count", models.PositiveIntegerField(default=0, help_text="SMS successfully sent.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_blasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_blasts",
                        to="Promotions.promotion",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when audience=site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_blasts",
                        to="Site.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
