# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


def seed_service_categories(apps, schema_editor):
    ServiceCategory = apps.get_model("ServiceRequests", "ServiceCategory")
    ServiceType = apps.get_model("ServiceRequests", "ServiceType")

    data = [
        ("Mechanical", [
            "Brake repair", "Engine repair", "Suspension", "Transmission", "Clutch",
            "Steering", "Exhaust system", "Cooling system", "Oil change", "Tune-up",
            "Timing belt", "Alternator", "Starter motor", "Fuel system",
        ]),
        ("Electrical", [
            "Battery replacement", "Wiring repair", "Lighting", "Alternator",
            "Starter", "Fuse replacement", "Dashboard instruments", "Power windows",
            "Central locking", "Air conditioning", "Audio system",
        ]),
        ("Bodywork", [
            "Panel beating", "Painting", "Dent removal", "Rust repair",
            "Windscreen replacement", "Bumper repair", "Frame straightening",
        ]),
        ("Tyres & wheels", [
            "Tyre replacement", "Wheel alignment", "Wheel balancing", "Puncture repair",
            "Tyre rotation", "Valve replacement",
        ]),
        ("General maintenance", [
            "Service", "Pre-purchase inspection", "Diagnostics", "Fluid top-up",
            "Filter replacement", "Wiper replacement",
        ]),
    ]
    for order, (cat_name, types) in enumerate(data):
        cat = ServiceCategory.objects.create(name=cat_name, order=order)
        for i, type_name in enumerate(types):
            ServiceType.objects.create(category=cat, name=type_name, order=i)


class Migration(migrations.Migration):

    dependencies = [
        ("ServiceRequests", "0005_servicerequest_labor_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("order", models.PositiveIntegerField(default=0, help_text="Display order")),
            ],
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Service categories",
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_types", to="ServiceRequests.servicecategory")),
            ],
            options={
                "ordering": ["category", "order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Category and type of service (e.g. Mechanical — Brake Repair)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="ServiceRequests.servicetype",
            ),
        ),
        migrations.RunPython(seed_service_categories, migrations.RunPython.noop),
    ]
