# Generated by Django 4.2.16 on 2026-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequests', '0007_servicerequest_vehicle_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(help_text='Additional details and notes'),
        ),
    ]
