# Generated by Django 4.2.16

from collections import defaultdict
from django.db import migrations
from django.utils import timezone


def backfill_sr_display_numbers(apps, schema_editor):
    ServiceRequest = apps.get_model("ServiceRequests", "ServiceRequest")
    DisplayNumberSequence = apps.get_model("common", "DisplayNumberSequence")

    by_year = defaultdict(list)
    for sr in ServiceRequest.objects.filter(display_number__isnull=True).order_by("created_at"):
        year = sr.created_at.year if sr.created_at else timezone.now().year
        by_year[year].append(sr)

    for year, srs in by_year.items():
        for i, sr in enumerate(srs, start=1):
            sr.display_number = f"SR-{year}-{i:04d}"
            sr.save(update_fields=["display_number"])
        DisplayNumberSequence.objects.update_or_create(
            prefix="SR",
            year=year,
            defaults={"last_value": len(srs)},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("ServiceRequests", "0009_servicerequest_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_sr_display_numbers, noop),
    ]
