# Generated by Django 4.2.16 on 2026-02-10 14:45

from collections import defaultdict

from django.db.models import Q
from django.db import migrations, models
from django.utils import timezone


def backfill_remaining_sr_display_numbers(apps, schema_editor):
    """Backfill any service requests with NULL or empty display_number before making field non-nullable."""
    import re
    ServiceRequest = apps.get_model("ServiceRequests", "ServiceRequest")
    DisplayNumberSequence = apps.get_model("common", "DisplayNumberSequence")
    qs = ServiceRequest.objects.filter(Q(display_number__isnull=True) | Q(display_number="")).order_by("created_at")
    if not qs.exists():
        return
    by_year = defaultdict(list)
    for sr in qs:
        year = sr.created_at.year if sr.created_at else timezone.now().year
        by_year[year].append(sr)
    for year, srs in by_year.items():
        max_num = 0
        for sr in ServiceRequest.objects.exclude(Q(display_number__isnull=True) | Q(display_number="")):
            m = re.match(rf"^SR-{year}-(\d+)$", sr.display_number or "")
            if m:
                max_num = max(max_num, int(m.group(1)))
        seq = DisplayNumberSequence.objects.filter(prefix="SR", year=year).first()
        if seq:
            max_num = max(max_num, seq.last_value)
        for i, sr in enumerate(srs, start=1):
            sr.display_number = f"SR-{year}-{max_num + i:04d}"
            sr.save(update_fields=["display_number"])
        DisplayNumberSequence.objects.update_or_create(
            prefix="SR", year=year, defaults={"last_value": max_num + len(srs)}
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequests', '0010_backfill_servicerequest_display_numbers'),
    ]

    operations = [
        migrations.RunPython(backfill_remaining_sr_display_numbers, noop),
        migrations.AlterField(
            model_name='servicerequest',
            name='display_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable ID, e.g. SR-2025-0042', max_length=20, unique=True),
        ),
    ]
