# Generated by Django 4.2.16 on 2026-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequests', '0012_add_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='display_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable ID, e.g. SALE-2025-0042 or SR-2025-0042', max_length=20, unique=True),
        ),
    ]
