# Generated by Django 4.2.16 on 2026-02-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequests', '0014_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional details and notes'),
        ),
    ]
