# Generated by Django 4.2.16 on 2024-11-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0001_initial"),
        ("ServiceRequests", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.product",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ServiceRequests.servicerequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="product_used",
            field=models.ManyToManyField(
                through="ServiceRequests.ProductUsage", to="Products.product"
            ),
        ),
    ]
