# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("ServiceRequests", "0008_alter_servicerequest_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="display_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable ID, e.g. SR-2025-0042",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
