# Generated by Django 4.2.16 on 2026-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequests', '0013_alter_servicerequest_display_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the transaction', max_length=20),
        ),
    ]
