# Generated by Django 4.2.16 on 2024-11-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Mechanics", "0001_initial"),
        ("Site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mechanics",
                to="Site.site",
            ),
        ),
    ]
