# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customers", "0002_customer_phone_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="receive_service_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Send automatic SMS/email reminders when vehicle service is due.",
            ),
        ),
    ]
