# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Mechanics', '0001_initial'),
        ('ServiceRequests', '0005_servicerequest_labor_cost'),
        ('Site', '0001_initial'),
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected slot duration in minutes.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Customers.customer')),
                ('mechanic', models.ForeignKey(blank=True, help_text='Optional: assign a mechanic in advance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Mechanics.mechanic')),
                ('service_request', models.ForeignKey(blank=True, help_text='Linked when converted to a service request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='ServiceRequests.servicerequest')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Site.site')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Vehicles.vehicle')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
