# Generated by Django 4.2.16

from collections import defaultdict
from django.db import migrations
from django.utils import timezone


def backfill_apt_display_numbers(apps, schema_editor):
    Appointment = apps.get_model("Appointments", "Appointment")
    DisplayNumberSequence = apps.get_model("common", "DisplayNumberSequence")

    by_year = defaultdict(list)
    for apt in Appointment.objects.filter(display_number__isnull=True).order_by("created_at"):
        year = apt.created_at.year if apt.created_at else timezone.now().year
        by_year[year].append(apt)

    for year, apts in by_year.items():
        for i, apt in enumerate(apts, start=1):
            apt.display_number = f"APT-{year}-{i:04d}"
            apt.save(update_fields=["display_number"])
        DisplayNumberSequence.objects.update_or_create(
            prefix="APT",
            year=year,
            defaults={"last_value": len(apts)},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("Appointments", "0002_appointment_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_apt_display_numbers, noop),
    ]
