# Generated by Django 4.2.16 on 2024-11-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Invoices", "0001_initial"),
        ("ServiceRequests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="service_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ServiceRequests.servicerequest",
            ),
        ),
    ]
