# Generated by Django 4.2.16 on 2026-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_invoice_discount_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('momo', 'MoMo (Mobile Money)'), ('pos', 'POS (Card)')], help_text='How the customer paid (when paid=True)', max_length=20, null=True),
        ),
    ]
