# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("Invoices", "0004_add_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="display_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable ID, e.g. INV-2025-00001",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
