# Generated by Django 4.2.16

from collections import defaultdict
from django.db import migrations
from django.utils import timezone


def backfill_invoice_display_numbers(apps, schema_editor):
    Invoice = apps.get_model("Invoices", "Invoice")
    DisplayNumberSequence = apps.get_model("common", "DisplayNumberSequence")

    # Group by year, assign sequential numbers
    by_year = defaultdict(list)
    for inv in Invoice.objects.filter(display_number__isnull=True).order_by("created_at"):
        year = inv.created_at.year if inv.created_at else timezone.now().year
        by_year[year].append(inv)

    for year, invoices in by_year.items():
        for i, inv in enumerate(invoices, start=1):
            inv.display_number = f"INV-{year}-{i:05d}"
            inv.save(update_fields=["display_number"])
        # Prime the sequence so new records continue from here
        DisplayNumberSequence.objects.update_or_create(
            prefix="INV",
            year=year,
            defaults={"last_value": len(invoices)},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("Invoices", "0005_invoice_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_invoice_display_numbers, noop),
    ]
