# Generated by Django 4.2.16 on 2024-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_serviced",
            field=models.DateField(blank=True, null=True),
        ),
    ]
