# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisplayNumberSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(db_index=True, max_length=10)),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Display number sequence",
                "verbose_name_plural": "Display number sequences",
                "unique_together": {("prefix", "year")},
            },
        ),
    ]
